version: '3.8'

services:
  composer:
    container_name: composer_paypal_service
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html

  console:
    container_name: console_paypal_service
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: [ 'php', '/var/www/html/bin/console' ]
  php83:
    build:
        context: ./dockerfiles
        dockerfile: test.dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"

volumes:
  db: